import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "@/components/SessionProvider";
import Header from "@/components/UI/Header";
import Footer from "@/components/UI/Footer";
import {Poppins} from "next/font/google";
import ShowHeader from "@/components/UI/ShowHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
    subsets:["latin"],
    weight:["400"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.className} antialiased xl:px-64 px-4 flex flex-col min-h-screen`}
      >
            <Provider>
                <ShowHeader>
                    <Header/>
                </ShowHeader>
                    <main className="flex-1">
                        {children}
                        <video id="localVideo" autoPlay playsInline muted></video>
                    </main>
                <Footer/>
            </Provider>
      </body>
    </html>
  );
}
